# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(656, 436)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 621, 381))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.generate = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.generate.setObjectName("generate")
        self.gridLayout.addWidget(self.generate, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.numbers = QtWidgets.QListWidget(parent=self.gridLayoutWidget)
        self.numbers.setObjectName("numbers")
        self.gridLayout.addWidget(self.numbers, 1, 0, 1, 4)
        self.load = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.load.setObjectName("load")
        self.gridLayout.addWidget(self.load, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.average = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.average.setMaximumSize(QtCore.QSize(100, 16777215))
        self.average.setObjectName("average")
        self.gridLayout.addWidget(self.average, 2, 1, 1, 1)
        self.madiana = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.madiana.setMaximumSize(QtCore.QSize(100, 16777215))
        self.madiana.setObjectName("madiana")
        self.gridLayout.addWidget(self.madiana, 3, 1, 1, 1)
        self.dominanta = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.dominanta.setMaximumSize(QtCore.QSize(100, 16777215))
        self.dominanta.setObjectName("dominanta")
        self.gridLayout.addWidget(self.dominanta, 4, 1, 1, 1)
        self.averageGeo = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.averageGeo.setMaximumSize(QtCore.QSize(100, 16777215))
        self.averageGeo.setObjectName("averageGeo")
        self.gridLayout.addWidget(self.averageGeo, 5, 1, 1, 1)
        self.n = QtWidgets.QTextEdit(parent=self.gridLayoutWidget)
        self.n.setMaximumSize(QtCore.QSize(50, 20))
        self.n.setObjectName("n")
        self.gridLayout.addWidget(self.n, 0, 3, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "Dominanta:"))
        self.label_3.setText(_translate("Dialog", "Mediana:"))
        self.generate.setText(_translate("Dialog", "Generuj"))
        self.label_2.setText(_translate("Dialog", "Średnia:"))
        self.load.setText(_translate("Dialog", "Wczytaj"))
        self.label.setText(_translate("Dialog", "N:"))
        self.label_5.setText(_translate("Dialog", "Śr. Geometryczna:"))
